create table zepto(
sku_id serial primary key,
category varchar(120),
name varchar(150),
mrp numeric(8,2),
discountPercent numeric(5,2),
availableQuantity integer,
discountedSellingPrice numeric(8,2),
weightInGms integer,
outOfStock boolean,
quantity integer
);

--- DATA EXPLORATION ---


--- COUNT OD ROWS ---

SELECT COUNT(*) FROM ZEPTO;

--- CHECKING SAMPLE DATA ---

SELECT * FROM ZEPTO LIMIT 20; 

--- CHECKING NULL VALUES ---

SELECT * FROM ZEPTO
WHERE NAME IS NULL 
OR
CATEGORY IS NULL
OR
MRP IS NULL
OR
DISCOUNTPERCENT IS NULL
OR
AVAILABLEQUANTITY IS NULL
OR
DISCOUNTEDSELLINGPRICE IS NULL
OR
WEIGHTINGMS IS NULL
OR
OUTOFSTOCK IS NULL
OR
QUANTITY IS NULL;

--- CHECKING DIFFERENT PRODUCT CATEGORIES ---

SELECT DISTINCT CATEGORY FROM ZEPTO
ORDER BY CATEGORY;

--- CHECKING PRODUCTS IN STOCK VS OUT OF STOCK ---

SELECT OUTOFSTOCK , COUNT(SKU_ID)FROM ZEPTO
GROUP BY OUTOFSTOCK;


--- CHECKING NAME , PRESENT MULTIPLE TIMES ---

SELECT NAME, COUNT(SKU_ID) AS "NUMBER OF SKUS" FROM ZEPTO
GROUP BY NAME
HAVING COUNT(SKU_ID) > 1
ORDER BY COUNT(SKU_ID) DESC; 

--- DATA CLEANING ---

--- CHECKING PRODUCTS WITH PRICE = 0 

SELECT * FROM ZEPTO
WHERE MRP = 0 AND DISCOUNTEDSELLINGPRICE = 0;

DELETE FROM ZEPTO
WHERE MRP = 0; 

--- CONVERT PAISE TO RUPEES ---

UPDATE ZEPTO
SET MRP = MRP/100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100.0;


SELECT MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO;

-- Q01. FIND THE TOP 10 BEST-VALUE PRODUCTS BASED ON THE DISCOUNT PERCENTAGE. --

SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;

-- Q2. WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK --

SELECT DISTINCT NAME, MRP
FROM ZEPTO
WHERE OUTOFSTOCK = TRUE AND MRP > 300
ORDER BY MRP DESC;

-- Q03. CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY --

SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;

-- Q04. FIND ALL PRODUCTS WHERE MRP IS GREATER THAN ₹500 AND DISCOUNT IS LESS THAN 10%. --

SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP > 500 AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC, DISCOUNTPERCENT DESC;

-- Q05. IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE. --

SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT), 2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;

-- Q06. FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUE. --

SELECT DISTINCT NAME, WEIGHTINGMS, DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS, 2) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM;

-- Q07. GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW, MEDIUM, BULK. --

SELECT DISTINCT NAME, WEIGHTINGMS,
CASE 
    WHEN WEIGHTINGMS < 1000 THEN 'LOW'
    WHEN WEIGHTINGMS < 5000 THEN 'MEDIUM'
    ELSE 'BULK'
END AS WEIGHT_CATEGORY
FROM ZEPTO;

-- Q08. WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY --

SELECT CATEGORY,
SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;


